version: "3"
services:
  web:
    restart: always
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
  app:
    command: bundle exec puma -C config/puma.rb
    image: populate/decidim:0.1
    volumes:
      - app_file_storage:/app/public/system/
      - app_assets:/app/public/assets/
      - app_logs:/app/logs/
      - app_bundle:/app/vendor/bundle
    ports:
      - "3000"
    depends_on:
      - db
  db:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=decidim
      - DB_PASS=decidim
      - DB_NAME=decidim
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  app_assets:
  app_file_storage:
  app_logs:
  app_bundle:
  db_data:
